#!/usr/bin/env bash
set -euo pipefail

I3_CONF="$HOME/.config/i3/config"
PICOM_CONF_DIR="$HOME/.config/picom"
PICOM_CONF="$PICOM_CONF_DIR/picom.conf"

# 1. Install
sudo pacman -Syu --noconfirm picom

# 2. Idempotent picom config
mkdir -p "$PICOM_CONF_DIR"
cat > "$PICOM_CONF" <<'EOF'
backend = "glx";
vsync = true;
shadow = false;
fading = true;
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 5;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'slop'"
];
EOF

# 3. Inject into i3 config (idempotent)
mkdir -p "$(dirname "$I3_CONF")"
touch "$I3_CONF"

if ! grep -q "AUTOGENERATED UI STARTUP" "$I3_CONF"; then
    cat >> "$I3_CONF" <<EOF

# --- AUTOGENERATED UI STARTUP ---
exec_always --no-startup-id pkill -x picom 2>/dev/null; picom --config $PICOM_CONF -b
# --- END AUTOGENERATED ---
EOF
fi

echo "Done. Reload i3 (mod+Shift+r) to apply."
