#!/usr/bin/env bash
set -euo pipefail

IMG_NAME="b-422.png"
IMG_URL="https://raw.githubusercontent.com/cliffordwilliam/dotfiles/main/$IMG_NAME"
IMG_DIR="$HOME/images"
IMG_PATH="$IMG_DIR/$IMG_NAME"
I3_CONF="$HOME/.config/i3/config"

# 1. Install
sudo pacman -Syu --noconfirm feh

# 2. Download only if not already present
mkdir -p "$IMG_DIR"
if [ ! -f "$IMG_PATH" ]; then
    curl -fL "$IMG_URL" -o "$IMG_PATH"
fi

# 3. Inject into i3 config (idempotent)
if ! grep -q "feh --bg-fill.*$IMG_NAME" "$I3_CONF"; then
    cat >> "$I3_CONF" <<EOF

# --- AUTOGENERATED WALLPAPER ---
exec_always --no-startup-id feh --bg-fill $IMG_PATH
# --- END AUTOGENERATED ---
EOF
fi

echo "Wallpaper provisioned."
